version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.24.8
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: 'none'
      CLUSTER_HOSTNAME: 'node1'
      GRPC_ENABLED: 'true'
